### ISSUE TITLE
Add tire model

### ISSUE THREAD

**Issue by gilberta** [gilberta/SSPA#1]
Model should have inputs of slip angle, camber and normal load and output of lateral force. :)

**Comment by mjgeary** [comment]
What units would you like?

**Comment by mjgeary** [comment]
Bitch please.

**Comment by mjgeary** [comment]
Also, can the tire model's Tire Unique Paramters be stored in a .mat to be pulled from the workspace? I think that would be better than hard coded. Do you?

**Comment by gilberta** [comment]
Units should be Newtons, meters, kilograms, and degrees. Angles should adhere to SAE conventions.

**Comment by gilberta** [comment]
Yeah I think that would be good.
