### ISSUE TITLE
Fix naming scheme

### ISSUE THREAD

**Issue by gilberta** [gilberta/SSPA#3]
All variables should have clear names, no acronyms. Also change also structures from 'r' and 'f'  to ' 'axleRear' and 'axleFront'.

**Comment by mjgeary** [comment]
http://www.google.ca/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CB8QFjAA&url=http%3A%2F%2Fwww.ee.columbia.edu%2F~marios%2Fmatlab%2FMatlabStyle1p5.pdf&ei=X1DBVK3xApL7sATRgoLQCQ&usg=AFQjCNGw4rFCA7ukV8yipj864ey5h4wNMw&sig2=cyVIeMvrIG_6W3ope799MQ&bvm=bv.83829542,d.cWc
